# Generated by Django 5.0.4 on 2025-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
