# Generated by Django 5.0.4 on 2025-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_material_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carbon_data', models.JSONField(blank=True, null=True)),
                ('carbon_insight', models.TextField(blank=True, null=True)),
                ('waste_data', models.JSONField(blank=True, null=True)),
                ('waste_insight', models.TextField(blank=True, null=True)),
                ('design_data', models.JSONField(blank=True, null=True)),
                ('design_insight', models.TextField(blank=True, null=True)),
                ('combined_insight', models.TextField(blank=True, null=True)),
                ('graph_metrics', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
