# Generated by Django 5.0.4 on 2025-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
