# Generated by Django 5.0.4 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_project_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='combined_forecasting',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
