# Generated by Django 5.0.4 on 2025-05-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_project_combined_forecasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='carbon_insight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
