# Generated by Django 5.0.4 on 2025-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_project_carbon_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='design_insight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='waste_insight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
