# Generated by Django 5.0.4 on 2025-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_material_city_material_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='city',
        ),
        migrations.RemoveField(
            model_name='material',
            name='country',
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
