# Generated by Django 5.0.4 on 2025-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_remove_material_city_remove_material_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
