# Generated by Django 5.0.4 on 2025-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_project_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leed_certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='well_certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
