# Generated by Django 5.0.4 on 2025-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leed_certification_insight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='well_certification_insight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
