# Generated by Django 5.0.4 on 2025-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_project_leed_certification_insight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leed_combined_forecasting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='leed_graph_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='well_combined_forecasting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='well_graph_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
