# Generated by Django 5.0.4 on 2025-06-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_project_leed_combined_forecasting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='combined_forecasting',
        ),
        migrations.RemoveField(
            model_name='project',
            name='combined_insight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='graph_metrics',
        ),
    ]
