# Generated by Django 5.0.4 on 2025-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_remove_project_combined_forecasting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leed_scorecard',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
