# Generated by Django 5.0.4 on 2025-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_project_leed_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='well_scorecard',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
