# Generated by Django 5.0.4 on 2025-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_project_well_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_occupant_load',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='floors',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
