# Generated by Django 5.0.4 on 2025-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_projectteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
