# Generated by Django 5.0.4 on 2025-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_project_end_time_project_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
