# Generated by Django 5.0.4 on 2025-06-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_document_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='sub_title',
            new_name='type',
        ),
    ]
