# Generated by Django 5.0.4 on 2025-06-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_rename_sub_title_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
